#!/usr/bin/env python3

# TODO
import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    # ensure user inputted command line argument is a tweet address
    screenName = sys.argv[1] 
    if screenName[0] != "@":
        sys.exit("Usage: ./tweets @screen_name")
        
    # ensure twitter address exists
    tweets = get_user_timeline(screenName.strip("@"), 50)
    if tweets == None:
        sys.exit("Twitter address does not exist")
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    score = 0
    
    # iterate through each user tweet
    for tweet in tweets:
        score += analyzer.analyze(tweet)

    # color the message based on the score returned from analyzer
    if score > 0.0:
        print(colored("1 I love you, @world", "green"))
    elif score < 0.0:
        print(colored("-1 I hate you, @world", "red"))
    else:
        print(colored("0 hello, @world", "yellow"))

if __name__ == "__main__":
    main()